require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AudiosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Audio. As you add validations to Audio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AudiosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET index' do
    it 'assigns all audios as @audios' do
      audio = Audio.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:audios)).to eq([audio])
    end
  end

  describe 'GET show' do
    it 'assigns the requested audio as @audio' do
      audio = Audio.create! valid_attributes
      get :show, { id: audio.to_param }, valid_session
      expect(assigns(:audio)).to eq(audio)
    end
  end

  describe 'GET new' do
    it 'assigns a new audio as @audio' do
      get :new, {}, valid_session
      expect(assigns(:audio)).to be_a_new(Audio)
    end
  end

  describe 'GET edit' do
    it 'assigns the requested audio as @audio' do
      audio = Audio.create! valid_attributes
      get :edit, { id: audio.to_param }, valid_session
      expect(assigns(:audio)).to eq(audio)
    end
  end

  describe 'POST create' do
    describe 'with valid params' do
      it 'creates a new Audio' do
        expect do
          post :create, { audio: valid_attributes }, valid_session
        end.to change(Audio, :count).by(1)
      end

      it 'assigns a newly created audio as @audio' do
        post :create, { audio: valid_attributes }, valid_session
        expect(assigns(:audio)).to be_a(Audio)
        expect(assigns(:audio)).to be_persisted
      end

      it 'redirects to the created audio' do
        post :create, { audio: valid_attributes }, valid_session
        expect(response).to redirect_to(Audio.last)
      end
    end

    describe 'with invalid params' do
      it 'assigns a newly created but unsaved audio as @audio' do
        post :create, { audio: invalid_attributes }, valid_session
        expect(assigns(:audio)).to be_a_new(Audio)
      end

      it "re-renders the 'new' template" do
        post :create, { audio: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT update' do
    describe 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested audio' do
        audio = Audio.create! valid_attributes
        put :update, { id: audio.to_param, audio: new_attributes }, valid_session
        audio.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested audio as @audio' do
        audio = Audio.create! valid_attributes
        put :update, { id: audio.to_param, audio: valid_attributes }, valid_session
        expect(assigns(:audio)).to eq(audio)
      end

      it 'redirects to the audio' do
        audio = Audio.create! valid_attributes
        put :update, { id: audio.to_param, audio: valid_attributes }, valid_session
        expect(response).to redirect_to(audio)
      end
    end

    describe 'with invalid params' do
      it 'assigns the audio as @audio' do
        audio = Audio.create! valid_attributes
        put :update, { id: audio.to_param, audio: invalid_attributes }, valid_session
        expect(assigns(:audio)).to eq(audio)
      end

      it "re-renders the 'edit' template" do
        audio = Audio.create! valid_attributes
        put :update, { id: audio.to_param, audio: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE destroy' do
    it 'destroys the requested audio' do
      audio = Audio.create! valid_attributes
      expect do
        delete :destroy, { id: audio.to_param }, valid_session
      end.to change(Audio, :count).by(-1)
    end

    it 'redirects to the audios list' do
      audio = Audio.create! valid_attributes
      delete :destroy, { id: audio.to_param }, valid_session
      expect(response).to redirect_to(audios_url)
    end
  end

end
